name: HighResear
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=10.2.89
  - gfortran=11.2.0
  - jupyter=1.0.0
  - multinest=3.10
  - pip=21.2.4
  - python=3.9.7
  - pytorch=1.10.1
  - pip:
    - cloudpickle
    - dawgz==0.4.1
    - joblib==1.1.0
    - lampe==0.7.2
    - petitradtrans==2.3.6
    - wandb==0.13.3
    - zuko==0.1.3
